### ISSUE TITLE
Can not use package without Sitegeist.Papertiger

### ISSUE THREAD

**Issue by ger4003** [networkteam/Networkteam.FusionForm.Altcha#1]
When requiring this pacakge without Sitegiest.Papertiger being available, an exception is thrown. This is because the provided nodeType `Networkteam.FusionForm.Altcha:PaperTiger.Field.Captcha:` is based on Papertiger nodeTypes.

```yaml
Networkteam.FusionForm.Altcha:PaperTiger.Field.Captcha:
  ui:
    label: i18n
    icon: resource://Networkteam.FusionForm.Altcha/Icons/altcha.svg
    group: form.special
  superTypes:
    'Sitegeist.PaperTiger:Field': true
    'Sitegeist.PaperTiger:Mixin.Name': false
```
